{
 "title": "Backend Logs",
 "panels": [
  {
   "title": "Logs Backend / ALL",
   "type": "logs",
   "gridPos": { "x": 0, "y": 6, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"backend\"}"
    }
   ]
  },
  {
   "title": "Logs Backend / ERROR",
   "type": "logs",
   "gridPos": { "x": 12, "y": 6, "w": 12, "h": 10 },
   "targets": [
    {
     "expr": "{service=\"nginx\"} |~ \" 5[0-9][0-9] \""
    }
   ]
  },
  {
   "title": "Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "count_over_time({service=\"nginx\"}[1m])"
    }
   ]
  },
  {
   "title": "Logs Backend / FATAL",
   "type": "logs",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "{service=\"nginx\"} |= \"FATAL\""
    }
   ]
  }
 ]
}