"""add updated_at triggers

Revision ID: 0d6473579283
Revises: 3bc95735cbba
Create Date: 2026-01-09 11:36:42.441244

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d6473579283"
down_revision: Union[str, Sequence[str], None] = "3bc95735cbba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
       NEW.updated_at = now();
       RETURN NEW;
    END;
    $$ LANGUAGE plpgsql;
    """)

    # Criar trigger para tabela users
    op.execute("""
    CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
    """)

    # Criar trigger para tabela properties
    op.execute("""
    CREATE TRIGGER update_properties_updated_at
    BEFORE UPDATE ON properties
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS update_users_updated_at ON users")
    op.execute("DROP TRIGGER IF EXISTS update_properties_updated_at ON properties")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")
    # ### end Alembic commands ###
