"""add relationships to property, property tag and tag models

Revision ID: 18f87ff57019
Revises: 643e9607d046
Create Date: 2026-01-18 15:56:39.880370

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "18f87ff57019"
down_revision: Union[str, Sequence[str], None] = "643e9607d046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_properties_public_id"), "properties", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_properties_public_id"), "properties", ["public_id"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
