"""refactor(property): remove user_id

Revision ID: 244769102b62
Revises: 5d97ffc5ddd2
Create Date: 2026-02-03 20:32:08.691687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244769102b62'
down_revision: Union[str, Sequence[str], None] = '5d97ffc5ddd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_user_id'), table_name='properties')
    op.drop_constraint(op.f('properties_user_id_fkey'), 'properties', type_='foreignkey')
    op.drop_column('properties', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('properties_user_id_fkey'), 'properties', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_properties_user_id'), 'properties', ['user_id'], unique=False)
    # ### end Alembic commands ###
