"""add photos public id

Revision ID: 377965c51823
Revises: 18f87ff57019
Create Date: 2026-01-21 18:05:15.784079

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "377965c51823"
down_revision: Union[str, Sequence[str], None] = "18f87ff57019"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("photos", sa.Column("public_id", sa.UUID(), nullable=False))
    op.add_column("photos", sa.Column("storage_key", sa.String(), nullable=True))
    op.alter_column("photos", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False)
    op.drop_index(op.f("ix_photos_id"), table_name="photos")
    op.create_unique_constraint(op.f("uq_photos_public_id"), "photos", ["public_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_photos_public_id"), "photos", type_="unique")
    op.create_index(op.f("ix_photos_id"), "photos", ["id"], unique=False)
    op.alter_column("photos", "updated_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True)
    op.drop_column("photos", "storage_key")
    op.drop_column("photos", "public_id")
    # ### end Alembic commands ###
