"""update property and add address model

Revision ID: 5bf46e6e4a62
Revises: 90213a45fda6
Create Date: 2026-01-10 15:17:01.069598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf46e6e4a62'
down_revision: Union[str, Sequence[str], None] = '90213a45fda6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('neighborhood', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('complement', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zip_code', 'street', 'number', 'complement', name='uq_address_unique_location')
    )
    op.create_index('ix_address_geo', 'addresses', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_addresses_zip_code'), 'addresses', ['zip_code'], unique=False)
    op.add_column('properties', sa.Column('address_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_properties_address_id'), 'properties', ['address_id'], unique=False)
    op.create_foreign_key('fk_properties_address_id', 'properties', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True))
    op.drop_constraint('fk_properties_address_id', 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_address_id'), table_name='properties')
    op.drop_column('properties', 'address_id')
    op.drop_index(op.f('ix_addresses_zip_code'), table_name='addresses')
    op.drop_index('ix_address_geo', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
