"""upgrade unique constraint on addresses

Revision ID: 5d97ffc5ddd2
Revises: 1bf2566ebc02
Create Date: 2026-02-03 15:51:54.740000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5d97ffc5ddd2"
down_revision: Union[str, Sequence[str], None] = "1bf2566ebc02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_address_unique_location"), "addresses", type_="unique")
    op.create_unique_constraint(
        "uq_address_unique_location",
        "addresses",
        ["zip_code", "state", "city", "neighborhood", "street", "number", "complement"],
    )
    op.add_column("properties", sa.Column("profile_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_properties_profile_id"), "properties", ["profile_id"], unique=False)
    op.execute("""
        UPDATE properties p
        SET profile_id = up.id
        FROM user_profiles up
        WHERE up.user_id = p.user_id
            AND p.profile_id IS NULL
    """)
    op.execute("""
        UPDATE properties
        SET profile_id = 17
        WHERE profile_id IS NULL
    """)
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM properties WHERE profile_id IS NULL
            ) THEN
                RAISE EXCEPTION 'profile_id contains NULL';
            END IF;
        END$$;
    """)
    op.alter_column("properties", "profile_id", nullable=False)
    op.create_foreign_key(
        op.f("fk_properties_profile_id_user_profiles"),
        "properties",
        "user_profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(op.f("uq_user_profiles_public_id"), "user_profiles", type_="unique")
    op.create_index(op.f("ix_user_profiles_public_id"), "user_profiles", ["public_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_profiles_public_id"), table_name="user_profiles")
    op.create_unique_constraint(
        op.f("uq_user_profiles_public_id"), "user_profiles", ["public_id"], postgresql_nulls_not_distinct=False
    )
    op.drop_constraint(op.f("fk_properties_profile_id_user_profiles"), "properties", type_="foreignkey")
    op.drop_index(op.f("ix_properties_profile_id"), table_name="properties")
    op.drop_column("properties", "profile_id")
    op.drop_constraint("uq_address_unique_location", "addresses", type_="unique")
    op.create_unique_constraint(
        op.f("uq_address_unique_location"),
        "addresses",
        ["zip_code", "street", "number", "complement"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
