"""add property public id

Revision ID: 643e9607d046
Revises: 7e899b1a076d
Create Date: 2026-01-18 10:31:58.514226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '643e9607d046'
down_revision: Union[str, Sequence[str], None] = '7e899b1a076d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('public_id', sa.String(length=21), nullable=True))
    op.execute("""
               UPDATE properties
               SET public_id = substr(md5(random()::text), 1, 21)
    """)
    op.alter_column(
        'properties',
        'public_id',
        nullable=False
    )
    op.create_unique_constraint(
        'uq_properties_public_id',
        'properties',
        ['public_id']
    )
    op.create_index(op.f('ix_properties_public_id'), 'properties', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_public_id'), table_name='properties')
    op.drop_column('properties', 'public_id')
    # ### end Alembic commands ###
