"""add photos_table

Revision ID: 8337ae9e805f
Revises: e1c8a94c0aae
Create Date: 2026-01-15 10:43:44.666142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8337ae9e805f'
down_revision: Union[str, Sequence[str], None] = 'e1c8a94c0aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('facade', 'exterior', 'street_view', 'aerial', 'map', 'internal', 'amenities', 'floorplan', 'render', 'document', 'general', name='photo_category_enum', native_enum=False), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'private', 'unlisted', name='photo_visibility_enum', native_enum=False), nullable=False),
    sa.Column('processing_status', sa.Enum('pending', 'uploaded', 'processing', 'ready', 'failed', name='photo_processing_status_enum', native_enum=False), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('is_cover', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('position >= 0', name='ck_photos_position_positive'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_photos_property_id_properties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=False)
    op.create_index(op.f('ix_photos_property_id'), 'photos', ['property_id'], unique=False)
    op.create_index('ix_photos_property_order', 'photos', ['property_id', 'position'], unique=False)
    op.create_index('ux_photos_content_hash', 'photos', ['content_hash'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ux_photos_one_cover_per_property', 'photos', ['property_id'], unique=True, postgresql_where=sa.text('is_cover = true AND deleted_at IS NULL'))
    op.create_index('ux_photos_property_position', 'photos', ['property_id', 'position'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_photos_property_position', table_name='photos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ux_photos_one_cover_per_property', table_name='photos', postgresql_where=sa.text('is_cover = true AND deleted_at IS NULL'))
    op.drop_index('ux_photos_content_hash', table_name='photos', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_photos_property_order', table_name='photos')
    op.drop_index(op.f('ix_photos_property_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
