# # Upstreams
# upstream backend_api {
#     server backend:3000;
# }

# upstream another_service {
#     server another_backend:4000;
# }

# server {
#     listen 80;

#     # Security headers
#     add_header X-Content-Type-Options nosniff;
#     add_header X-Frame-Options DENY;
#     add_header X-XSS-Protection "1; mode=block";

#     # Logging
#     access_log /var/log/nginx/backend_access_log main;

#     # Proxy to main backend
#     location / {
#         proxy_pass http://backend_api;
#         proxy_http_version 1.1;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Photo $scheme;

#         # Cache
#         proxy_cache STATIC;
#         proxy_cache_valid 200 1m;
#         proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
#     }
# }
