from fastapi import status

DOMAIN_ERROR_HTTP_MAP = {
    # AUTH EXCEPTIONS
    "PERMISSION_DENIED": status.HTTP_401_UNAUTHORIZED,
    "INVALID_CREDENTIALS": status.HTTP_400_BAD_REQUEST,
    # USER EXCEPTIONS
    "INVALID_EMAIL": status.HTTP_422_UNPROCESSABLE_CONTENT,
    "INVALID_USER_PUBLIC_ID": status.HTTP_422_UNPROCESSABLE_CONTENT,
    "EMAIL_ALREADY_REGISTERED": status.HTTP_409_CONFLICT,
    "USER_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    # PROFILE EXCEPTIONS
    "USER_PROFILE_NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "USER_PROFILE_ALREADY_REGISTERED": status.HTTP_409_CONFLICT,
    "INVALID_PROFILE_PUBLIC_ID": status.HTTP_422_UNPROCESSABLE_CONTENT,
    "PROFILE_PUBLIC_ID_NOT_AVAILABLE": status.HTTP_409_CONFLICT,
    "INVALID_WORK_PHONE": status.HTTP_422_UNPROCESSABLE_CONTENT,
}


API_ERROR_HTTP_MAP = {
    # SCHEMA EXCEPTIONS
    "INVALID_PRICE_FILTERS": status.HTTP_400_BAD_REQUEST,
    "INVALID_MAP_BOUNDS": status.HTTP_400_BAD_REQUEST,
}
